### ISSUE TITLE
suport i do no how to import1

### ISSUE THREAD

**Issue by superboys2017** [nickurt/laravel-oxxa#2]
can you help me whit this
![image](https://user-images.githubusercontent.com/40305210/87972227-da1eac00-cac6-11ea-9aa7-93e22e4b315f.png)

**Comment by nickurt** [comment]
```php
use \nickurt\Oxxa\Facade as Oxxa;
```

**Comment by superboys2017** [comment]
![image](https://user-images.githubusercontent.com/40305210/87980104-54edc400-cad3-11ea-9995-653698a657f0.png)

![image](https://user-images.githubusercontent.com/40305210/87980128-5d45ff00-cad3-11ea-9ea2-d4a10c6a0d36.png)
